### ISSUE TITLE
Error running on windows

### ISSUE THREAD

**Issue by fmsouza** [tienph6m/emus#1]
I've run this command within Windows WSL:

```
user@localhost:~/projects/personal/my-app$ emus -h

        Error: Command failed with ENOENT: /home/user/.bin/android-sdk/emulator/emulator -list-avds
spawn /home/user/.bin/android-sdk/emulator/emulator ENOENT
        Error: The iOS Simulator is only available on macOS
```

**Comment by tienph6m** [comment]
Hi @fmsouza, thanks for the issue
Can you install `v0.3.0` and confirm if it fixes the issue?

**Comment by fmsouza** [comment]
It doesn't just tried

**Comment by tienph6m** [comment]
Can you confirm `emus --version` returns `0.3.0`? Also, did you get the same error?

**Comment by andrelind** [comment]
On my machine the emulators is not located under `android-sdk/emulator/emulator` but instead `android-sdk/tools/emulator`
Could it be fixed to check which path is available?

**Comment by fmsouza** [comment]
Ok, just found which was the problem. I'm on Windows with WSL. I have Android SDK installed on both sides (WSL and Windows itself), though only Windows side has emulators, as WSL is headless.

It's looking for the emulator on my $ANDROID_HOME, which was pointing to WSL, and so was not found.

Changing my $ANDROID_HOME to point to Windows main Android SDK under `/mnt/c/Users/MyUser/AppData/Local/Android/Sdk` (which is the place Android Studio installs as default) did the job!

Maybe what could have happened instead is a better log telling me the emulator is not available in the path, or so.

**Comment by tienph6m** [comment]
@fmsouza Thanks! That's really helpful, we definitely need better errors on Windows. I'll probably have the next version published in a few days, hopefully you can help test that version then since I don't have access to a Windows WSL machine.
@andrelind Please checkout `v0.4.0` and let me know if it fixes your issue.

**Comment by tienph6m** [comment]
@fmsouza @andrelind I've just published `v0.5.0`, please give it a try and let me know if it fixes the issues.

**Comment by andrelind** [comment]
With 0.5.0 all the available emulators shows up now!
But nothing happens when I try to start them :-/

**Comment by tienph6m** [comment]
@andrelind 
Can you run `android-sdk/tools/emulator -list-avds` to get the list of AVDs
and then run `./emulator -avd avdname` to start an AVD
I got this error
`PANIC: Missing emulator engine program for 'x86' CPU.`

Any reason why you can't upgrade your Android SDK tools?

**Comment by andrelind** [comment]
Sorry, had android-sdk installed via brew, when I removed that it worked like a charm :-)

**Comment by tienph6m** [comment]
That's great!
Yeah, the android-sdk from homebrew only includes the command line tools, you still need to use the `sdkmanager` to install other packages, including the new emulator. It's probably not a good idea to try and use `android-sdk/tools/emulator` to start the emulator, I'll remove that in the next version.

**Comment by tienph6m** [comment]
@fmsouza  I'm closing this, please re-open the issue if you still experience this in the latest version ;)
