### ISSUE TITLE
Error: Couldn't find the Android Emulator

### ISSUE THREAD

**Issue by patevs** [tienph6m/emus#2]
Running on Windows I get the following error:

```
Error:
        Couldn't find the Android Emulator in: 'C:\Users\MyUser\AppData\Local\Android\Sdk\'
        Make sure your $ANDROID_HOME environment variable is pointed to the correct SDK installation directory.
```

I am able to run `emulator -list-avds` successfully so am unsure why this error is occurring.

I am using:

node `v12.16.2`
npm `6.14.4`
emus `0.7.0`

Any help would be appreciated!

**Comment by tienph6m** [comment]
Hi @patevs,
Could you install `v0.8.0` and try again?

**Comment by patevs** [comment]
Installed version `0.8.0` and works as expected. Thank you!
