### ISSUE TITLE
Add support to open emulator with flags (like -wipe-data)

### ISSUE THREAD

**Issue by itsashis4u** [tienph6m/emus#3]
https://stackoverflow.com/questions/6831698/android-eclipse-where-to-write-command-lines-like-emulator-wipe-data

**Comment by itsashis4u** [comment]
Also, thank you for this tool :)

**Comment by itsashis4u** [comment]
@tienph6m This make sense. Something like `emus -a -wipe-data` or `emus -wipe-data`. Can list all the supported flags in the help section

**Comment by tienph6m** [comment]
I just went through some of the startup options of the Android emulator and I don’t know if adding a `--wipe` flag is a good idea. It feels weird to just support the `-wipe-data` and not the other options. I also don’t wipe user data that often and if I want to do that, I probably would just reach for the `emulator` binary or the AVD Manager.

**Comment by itsashis4u** [comment]
I agree with your point. Will it be a good idea if you just forward any flags added while executing the `emus` command?

**Comment by tienph6m** [comment]
@itsashis4u Yeah that would allow users to have access to all the options, but I don't think that's a good idea 🤔 
I just thought of another way to do this. How about we have a flag to show the startup options after selecting the device (Start, Wipe, etc.). We only show these options when the flag is enabled. That way, users don't have to go through an extra step if they don't want (need) to, and when they do want the options, they can just select them from the prompt without having to remember the flags from the emulator command.
What do you think?

**Comment by itsashis4u** [comment]
Yes, this seems like a good idea

**Comment by tienph6m** [comment]
Hi @itsashis4u,
Sorry for the late follow up. I've just published `0.9.0-beta.0` with the `-s` flag to show the startup options. I'll probably have `v0.9.0` published within the next few days, please help test this beta version.

**Comment by itsashis4u** [comment]
I'll check it out

**Comment by itsashis4u** [comment]
Looks good to me! 👍

**Comment by itsashis4u** [comment]
Closing the issue

**Comment by tienph6m** [comment]
Thanks @itsashis4u, `v0.9.0` is up 🚀
